# Generated by Django 3.1 on 2022-04-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffMembers',
            new_name='StaffMember',
        ),
    ]
