# Generated by Django 4.0.4 on 2022-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220423_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
